# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering')], max_length=2, null=True),
        ),
    ]
