# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WebApp.Course'),
            preserve_default=False,
        ),
    ]
