# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20171003_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option_A', models.CharField(max_length=200, null=True)),
                ('option_B', models.CharField(max_length=200, null=True)),
                ('option_C', models.CharField(max_length=200, null=True)),
                ('option_D', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
