# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_auto_20171003_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='if_no_then',
        ),
        migrations.AddField(
            model_name='poll',
            name='options',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
