# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_auto_20171013_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='noq',
            field=models.IntegerField(null=True),
        ),
    ]
